name: 'Cached APT Install'
description: 'Install APT based packages and cache them for future runs.'
inputs:
  packages:
    description: 'Space delimited list of packages to install.'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Cache Packages
      uses: actions/cache@v2
      id: cached-apt-install-packages
        with:
          path: "~/cached-apt-install-packages"
          key: cached-apt-install-packages

    - name: Install Packages
      run: ${{ github.action_path }}/install.sh "~/cached-apt-install-packages" "${{ inputs.packages }}"
      shell: bash
