plugins:
  remark-preset-lint-consistent: true
  remark-preset-lint-recommended: true
  remark-lint-list-item-indent: true
  # Allow ATX-style headings (using #). Previously Trunk/remark was expecting
  # setext-style for certain heading levels which caused the "Unexpected ATX
  # heading, expected setext" errors. Setting this rule to 'atx' relaxes that.
  remark-lint-heading-style: [true, 'atx']
