# Repo-root Vale configuration for Trunk
StylesPath = .trunk/valestyles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Common, WriteGood, Microsoft
Ignore = .github/ISSUE_TEMPLATE/** CLAUDE.md

[*]
# Apply Code style to other files for comments
BasedOnStyles = Common
Ignore = **/.git/** .trunk/**
