on: [push]

jobs:
  install_packages:
    runs-on: ubuntu-latest
    name: Test job to install and cache APT packages (i.e. rolldice, dot).
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cached-apt-install-action@v1
        with:
          packages: rolldice dot
  test_packages_cache:
    needs: install_packages
    runs-on: ubuntu-latest
    name: Test job to verify cached APT packages (i.e. rolldice, dot).
    steps:
      - uses: actions/checkout@v2
      - run: |
        [ -d "~/cached-apt-install-packages" ] || exit 1;
        [ -d "~/cached-apt-install-packages/rolldice" ] || exit 2;
        [ -d "~/cached-apt-install-packages/dot" ] || exit 3;
      - shell: bash