name: Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run PR checks
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          npm run check:pr -- --base-ref "${{ github.base_ref }}" --head-ref "${{ github.head_ref }}" \
           --allow-admin-bypass
