name: Tests
on: [push, pull_request]

jobs:

  install:
    runs-on: ubuntu-latest
    name: Install and cache.
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache_key: ${{ env.GITHUB_JOB }}
          packages: dot rolldice

  verify:
    needs: install
    runs-on: ubuntu-latest
    name: Verify cached installs.
    steps:
      - uses: actions/checkout@v2
      - run: |
          [ -d "~/cached-apt-install-packages" ] || exit 1;
          [ -d "~/cached-apt-install-packages/dot" ] || exit 2;
          [ -d "~/cached-apt-install-packages/rolldice" ] || exit 3;        

  add_install:
    needs: verify
    runs-on: ubuntu-latest
    name: Add another install and cache.
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache_key: ${{ env.GITHUB_JOB }}
          packages: dot rolldice g++

  verify_add:
    needs: add_install
    runs-on: ubuntu-latest
    name: Verify added and cached install.
    steps:
      - uses: actions/checkout@v2
      - run: |
          [ -d "~/cached-apt-install-packages" ] || exit 4;
          [ -d "~/cached-apt-install-packages/dot" ] || exit 5;
          [ -d "~/cached-apt-install-packages/g++" ] || exit 6;
          [ -d "~/cached-apt-install-packages/rolldice" ] || exit 7;

  verify_cleanup:
    needs: verify_add
    runs-on: ubuntu-latest
    name: Verify omitted packages are cleaned up.
    steps:      
      - uses: ./
        with:
          cache_key: ${{ env.GITHUB_JOB }}_1
          packages: dot g++
      - run: |
          [ -d "~/cached-apt-install-packages" ] || exit 8;   
          [ -d "~/cached-apt-install-packages/dot" ] || exit 9;
          [ -d "~/cached-apt-install-packages/g++" ] || exit 10;
          [ -d "~/cached-apt-install-packages/rolldice" ] && exit 11;
  
  verify_isolation:
    needs: verify_add
    runs-on: ubuntu-latest
    name: Verify cache state is not shared.
    steps:      
      - uses: ./
        with:
          cache_key: ${{ env.GITHUB_JOB }}_1
          packages: show-motd
      - run: |
          [ -d "~/cached-apt-install-packages" ] || exit 12;
          [ -d "~/cached-apt-install-packages/motd" ] || exit 13;
          [ -d "~/cached-apt-install-packages/dot" ] && exit 14;
          [ -d "~/cached-apt-install-packages/g++" ] && exit 15;
          [ -d "~/cached-apt-install-packages/rolldice" ] && exit 16;

  no_packages:
    runs-on: ubuntu-latest
    name: No packages passed.
    steps:
      - name: Execute
        uses: .
        with:
          cache_key: ''
          packages: ''
        continue-on-error: true
      - name: Verify
        if: steps.execute.outcom != 'failure'
        run: exit 1

  package_not_found:
    runs-on: ubuntu-latest
    name: Package not found.
    steps:
      - name: Execute
        uses: .
        with:
          cache_key: ${{ env.GITHUB_JOB }}
          packages: package_that_doesnt_exist
        continue-on-error: true
      - name: Verify
        if: steps.execute.outcome != 'failure'
        run: exit 1
